# AutoReferee Configuration
config-version: 2
console-log: true
auto-update: true

allow-ties: false

delay-seconds:
  ready: 15
  completed: 180

# all paths relative to the server-root
local-storage:
  match-summary:
    directory: plugins/AutoReferee/summary
  local-database: plugins/AutoReferee/autoref.sdb

config-mode:
  tools:
    win-condition: GOLD_SPADE
    start-mechanism: GOLD_AXE
    protect-entities: GOLD_SWORD

lobby:
  world: autoref-lobby
  mode: manual
