name: AutoReferee
main: org.mctourney.autoreferee.AutoReferee
version: 2.8
author: "authorblues, net"
load: startup

softdepend:
  - WorldEdit

commands:
  autoref:
    aliases: [ar, autoreferee]
    description: AutoReferee configuration
    usage: /<command> [<action>] [args...]
  zone:
    description: Set a region's ownership
    usage: /<command> <team>|start
  zones:
    description: Show a list of all zones
    usage: /<command>
  matchinfo:
    aliases: [info, minfo, mi]
    description: Show info about current match
    usage: /<command>
  joinmatch:
    description: Join another player's match
    usage: /<command> <player>
  listmatches:
    aliases: [matchlist, matches]
    description: List all matches available on the server
    usage: /<command>
  leavematch:
    aliases: [lobby]
    description: Leave the current match
    usage: /<command>
  setaccess:
    description: Set access type of the current match
    usage: /<command> <type>
  jointeam:
    aliases: [join, j]
    description: Set player's team
    usage: /<command> [<team>] [<player>]
  leaveteam:
    aliases: leave
    description: Remove player's team
    usage: /<command> [<player>]
  ready:
    description: Mark team as ready to play
    usage: /<command> -tfyn
  viewinventory:
    aliases: vi
    description: View the inventory of the player
    usage: /<command> [-p] <player>
  artp:
    aliases: [atp]
    description: Teleport spectators safely
    usage: /<command> [<options>] <target>
  announce:
    aliases: [a, ann]
    description: Make an announcement to players and streamers
    usage: /<command> <message>
  broadcast:
    aliases: [b, bcast]
    description: Make a broadcast to players and streamers
    usage: /<command> <message>
  notify:
    aliases: [n]
    description: Notify streamers and referees of a matter of interest
    usage: /<command> <message>
  scoreboard:
    description: Replacement for Bukkit's /scoreboard command
    usage: /<command> ...
  time:
    description: Replacement for Minecraft's /time command
    usage: /<command> [set, add] <value>

permissions:
  autoreferee.*:
    description: Access to all AutoReferee features
    default: op
    children:
      autoreferee.admin: true
  autoreferee.admin:
    description: AutoReferee administrators
    default: false
    children:
      autoreferee.configure: true
      autoreferee.referee: true
  autoreferee.configure:
    description: AutoReferee configuration
    default: false
  autoreferee.streamer:
    description: AutoReferee streamer
    default: false
    children:
      autoreferee.referee: true
  autoreferee.referee:
    description: AutoReferee referees
    default: false
    children:
      autoreferee.player: true
  autoreferee.player:
    description: AutoReferee players
    default: true
    children:
      bukkit.command.kill: false
